services:
  - type: web
    name: quizai-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: OpenAI__ApiKey
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
      - key: Jwt__Secret
        sync: false
      - key: Admin__Email
        sync: false
      - key: Admin__Password
        sync: false
      - key: OpenAI__Model
        value: gpt-4o-mini
      - key: Jwt__ExpireMinutes
        value: "1440"
      - key: Jwt__Issuer
        value: QuizAI.Api
      - key: Jwt__Audience
        value: QuizAI.Desktop
    healthCheckPath: /swagger/index.html
    autoDeploy: true
